### PR TITLE
Various fixes.

### PR DESCRIPTION
**Pull request by siggiorn**
This is the result of addressing various linter issues which would sometimes uncover other things as well.

When you see a TODO comment, that's a question that I'd like addressed before accepting this PR.

I recommend looking at the diffs per commit, the first commit is the various changes, the second commit is changes where I create main() methods. I broke it up since the latter is mainly an indentation change and github had a hard time diffing them clearly when they were combined with the other changes.

### CODE REVIEW

**Comment by Stephanehk** [comment]
```
# TODO This is a little odd, changing a module level variable.
random_policy_data.changed_gt_rew_vec = False
```

In utils.random_policy_data.py, I have this `changed_gt_rew_vec` variable. I use it to pass information from advantage_learning_exp_handler.py to env.generate_random_policies.py. Essentially the flag serves an optimization where we avoid having to re-compute the value function multiple times per MDP, which is why it is set to false before a new MDP is processed. Do you have another suggestion for how to achieve this behavior without changing a module-level variable? I could add a `changed_gt_rew_vec` function argument instead of having this module-level variable in the first place.

**Comment by Stephanehk** [comment]
```
# TODO was this a bug?
env.set_custom_reward_function(rand_rew_vec)
```

No, if `set_rand_rew and not extended_SF` evaluates to true then it means we want to set a randomly generated reward function as the ground truth reward function, which is what this line is doing.

**Comment by Stephanehk** [comment]
```
# TODO Create main method.
if __name__ == "__main__":
    main()
```
Thanks for adding this!

**Comment by Stephanehk** [comment]
Are there any more TODOs I am missing? If not, I will merge this request and then incorporate your suggestions from [here](https://github.com/Stephanehk/Regret_Based_Reward_Learning/commit/a5009375095a3e7b9a8fb119b7ad760eb7bbad3a.

**Comment by siggiorn** [comment]
> 

Let's think about how this could be done differently but do it in a subsequent PR. I'll think a bit more about that.

**Pull request merged**
